#!/bin/bash

# Test Upload and Database Save Flow
echo "🧪 Testing Image Upload + Database Save Flow"
echo "============================================="

# Step 1: Test file upload API
echo ""
echo "📁 Step 1: Testing file upload to /api/upload..."

# Create a test image (1x1 pixel PNG)
echo "Creating test image..."
echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" | base64 -d > test-image.png

# Test upload API
echo "Uploading test image..."
UPLOAD_RESPONSE=$(curl -s -X POST -F "file=@test-image.png" http://localhost:5000/api/upload)
echo "Upload Response: $UPLOAD_RESPONSE"

# Extract URL from response
IMAGE_URL=$(echo $UPLOAD_RESPONSE | grep -o '"/uploads/[^"]*"' | sed 's/"//g')
echo "Extracted Image URL: $IMAGE_URL"

# Step 2: Test database save
echo ""
echo "💾 Step 2: Testing database save to /api/rows/[rowId]/images..."

# First, get available rows
echo "Getting available rows..."
ROWS_RESPONSE=$(curl -s http://localhost:5000/api/pages)
echo "Pages Response: $ROWS_RESPONSE"

# Create test data for database save
TEST_DATA='{
  "url": "'$IMAGE_URL'",
  "title": "Test Upload Image",
  "subtitle": "Generated by upload test script"
}'

echo "Test data to save: $TEST_DATA"

# Note: This would need an actual rowId from the application
echo ""
echo "⚠️  To complete database save test, you need:"
echo "1. A valid rowId from an existing row"
echo "2. POST to /api/rows/[rowId]/images with the test data above"

# Cleanup
rm -f test-image.png

echo ""
echo "✅ Upload API test completed"
echo "🔗 Next: Test via browser at http://localhost:5000"